import React, { useCallback, useEffect, useState } from 'react';
import { CircleDollarSign } from 'lucide-react';
import Swal from 'sweetalert2';
import { ModuleHeader } from '../components/shared/ModuleHeader';
import { useDashboard } from '../context/DashboardContext';
import { createExpense, createPayment, listExpenses, listLeases, listPayments, updatePayment, type ExpenseRecord, type PaymentRecord } from '../lib/api';
import { showError, showSuccess } from '../lib/alert';
import { formatCurrency, formatThaiDate } from '../lib/format';

export const FinancePage: React.FC = () => {
  const { summary, refetch: refetchDashboard } = useDashboard();
  const propertyId=summary?.property.id;
  const [payments,setPayments]=useState<PaymentRecord[]>([]); const [expenses,setExpenses]=useState<ExpenseRecord[]>([]); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{if(!propertyId)return;setLoading(true);try{const [p,e]=await Promise.all([listPayments(propertyId),listExpenses(propertyId)]);setPayments(p.items);setExpenses(e.items);}catch(err){showError('โหลดข้อมูลการเงินไม่สำเร็จ',err instanceof Error?err.message:'เกิดข้อผิดพลาด');}finally{setLoading(false);}},[propertyId]);
  useEffect(()=>{void load();},[load]);

  const addPayment=async()=>{if(!propertyId)return;try{const leases=(await listLeases(propertyId,{status:'ACTIVE'})).items;if(!leases.length){await Swal.fire('ไม่มีสัญญาที่ใช้งาน','สร้างสัญญาเช่าก่อนบันทึกค่าเช่า','warning');return;}const period=new Date().toISOString().slice(0,7);const r=await Swal.fire({title:'บันทึกรายการค่าเช่า',html:`<select id="p-lease" class="swal2-select"></select><input id="p-period" type="month" class="swal2-input" value="${period}"><input id="p-amount" type="number" class="swal2-input" placeholder="จำนวนเงิน"><select id="p-status" class="swal2-select"><option value="PAID">ชำระแล้ว</option><option value="PENDING">รอชำระ</option><option value="OVERDUE">ค้างชำระ</option></select>`,showCancelButton:true,confirmButtonText:'บันทึก',didOpen:()=>{const s=document.getElementById('p-lease') as HTMLSelectElement;leases.forEach(l=>s.add(new Option(`ห้อง ${l.room.number} · ${l.tenant.firstName} ${l.tenant.lastName}`,l.id)));},preConfirm:()=>{const leaseId=(document.getElementById('p-lease') as HTMLSelectElement).value;const period=(document.getElementById('p-period') as HTMLInputElement).value;const amount=Number((document.getElementById('p-amount') as HTMLInputElement).value);const status=(document.getElementById('p-status') as HTMLSelectElement).value as PaymentRecord['status'];if(!leaseId||!period||!Number.isInteger(amount)||amount<0){Swal.showValidationMessage('กรอกข้อมูลให้ถูกต้อง');return false;}return{leaseId,period,amount,status};}});if(!r.value)return;await createPayment(propertyId,r.value);await Promise.all([load(),refetchDashboard()]);await showSuccess('บันทึกค่าเช่าสำเร็จ','ข้อมูลลง PostgreSQL แล้ว');}catch(e){showError('บันทึกไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};
  const addExpense=async()=>{if(!propertyId)return;const today=new Date().toISOString().slice(0,10);const r=await Swal.fire({title:'บันทึกรายจ่าย',html:`<input id="e-cat" class="swal2-input" placeholder="หมวด เช่น ค่าซ่อม"><input id="e-amount" type="number" class="swal2-input" placeholder="จำนวนเงิน"><input id="e-date" type="date" class="swal2-input" value="${today}"><input id="e-note" class="swal2-input" placeholder="หมายเหตุ">`,showCancelButton:true,confirmButtonText:'บันทึก',preConfirm:()=>{const category=(document.getElementById('e-cat') as HTMLInputElement).value.trim();const amount=Number((document.getElementById('e-amount') as HTMLInputElement).value);const spentAt=(document.getElementById('e-date') as HTMLInputElement).value;const note=(document.getElementById('e-note') as HTMLInputElement).value.trim();if(!category||!spentAt||!Number.isInteger(amount)||amount<0){Swal.showValidationMessage('กรอกข้อมูลให้ถูกต้อง');return false;}return{category,amount,spentAt,note:note||null};}});if(!r.value)return;try{await createExpense(propertyId,r.value);await Promise.all([load(),refetchDashboard()]);await showSuccess('บันทึกรายจ่ายสำเร็จ','ข้อมูลลง PostgreSQL แล้ว');}catch(e){showError('บันทึกไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};
  const markPaid=async(p:PaymentRecord)=>{if(!propertyId)return;try{await updatePayment(propertyId,p.id,{status:'PAID'});await Promise.all([load(),refetchDashboard()]);}catch(e){showError('อัปเดตไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};

  return <div className="space-y-6"><ModuleHeader title="การเงิน & ค่าเช่า" subtitle={`ข้อมูลจริงจาก PostgreSQL · รายรับเดือนนี้ ${formatCurrency(summary?.finance.income.value??0)}`} icon={CircleDollarSign} actionLabel="+ บันทึกค่าเช่า" onAction={addPayment}/><div className="flex justify-end"><button onClick={addExpense} className="rounded-xl border border-primary-200 bg-white px-4 py-2 text-xs font-semibold text-primary-700">+ บันทึกรายจ่าย</button></div>
  <section className="rounded-2xl border border-surface-200 bg-white shadow-sm"><div className="border-b p-4 font-bold">รายการค่าเช่า</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-50 text-xs text-surface-500"><tr><th className="px-5 py-3">งวด</th><th className="px-4 py-3">ห้อง / ผู้เช่า</th><th className="px-4 py-3">จำนวน</th><th className="px-4 py-3">สถานะ</th><th className="px-5 py-3">จัดการ</th></tr></thead><tbody className="divide-y">{loading&&payments.length===0?<tr><td colSpan={5} className="py-8 text-center text-xs text-surface-400">กำลังโหลด...</td></tr>:payments.map(p=><tr key={p.id}><td className="px-5 py-3">{p.period}</td><td className="px-4 py-3">ห้อง {p.lease.room.number} · {p.lease.tenant.firstName} {p.lease.tenant.lastName}</td><td className="px-4 py-3 font-mono">{formatCurrency(p.amount)}</td><td className="px-4 py-3">{p.status==='PAID'?'ชำระแล้ว':p.status==='OVERDUE'?'ค้างชำระ':'รอชำระ'}</td><td className="px-5 py-3">{p.status!=='PAID'&&<button onClick={()=>void markPaid(p)} className="rounded-lg border px-2 py-1 text-xs">ทำเครื่องหมายว่าชำระแล้ว</button>}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl border border-surface-200 bg-white shadow-sm"><div className="border-b p-4 font-bold">รายจ่าย</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-50 text-xs text-surface-500"><tr><th className="px-5 py-3">วันที่</th><th className="px-4 py-3">หมวด</th><th className="px-4 py-3">จำนวน</th><th className="px-5 py-3">หมายเหตุ</th></tr></thead><tbody className="divide-y">{expenses.map(e=><tr key={e.id}><td className="px-5 py-3">{formatThaiDate(e.spentAt)}</td><td className="px-4 py-3">{e.category}</td><td className="px-4 py-3 font-mono">{formatCurrency(e.amount)}</td><td className="px-5 py-3 text-surface-500">{e.note||'-'}</td></tr>)}</tbody></table></div></section></div>;
};
