import React, { useCallback, useEffect, useState } from 'react';
import { Wrench } from 'lucide-react';
import Swal from 'sweetalert2';
import { ModuleHeader } from '../components/shared/ModuleHeader';
import { useDashboard } from '../context/DashboardContext';
import { createMaintenance, listMaintenance, listRooms, updateMaintenance, type MaintenanceRecord } from '../lib/api';
import { showError, showSuccess } from '../lib/alert';
import { formatThaiDateTime } from '../lib/format';

export const MaintenancePage:React.FC=()=>{const{summary,refetch:refetchDashboard}=useDashboard();const propertyId=summary?.property.id;const[items,setItems]=useState<MaintenanceRecord[]>([]);const[filter,setFilter]=useState<'ALL'|MaintenanceRecord['status']>('ALL');const load=useCallback(async()=>{if(!propertyId)return;try{setItems((await listMaintenance(propertyId,{status:filter==='ALL'?undefined:filter})).items);}catch(e){showError('โหลดแจ้งซ่อมไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}},[propertyId,filter]);useEffect(()=>{void load();},[load]);
const add=async()=>{if(!propertyId)return;try{const rooms=(await listRooms(propertyId)).items;if(!rooms.length){await Swal.fire('ไม่มีห้องพัก','','warning');return;}const r=await Swal.fire({title:'บันทึกแจ้งซ่อม',html:'<select id="m-room" class="swal2-select"></select><input id="m-title" class="swal2-input" placeholder="รายละเอียดปัญหา">',showCancelButton:true,confirmButtonText:'บันทึก',didOpen:()=>{const s=document.getElementById('m-room') as HTMLSelectElement;rooms.forEach(room=>s.add(new Option(`ห้อง ${room.number}`,room.id)));},preConfirm:()=>{const roomId=(document.getElementById('m-room') as HTMLSelectElement).value;const title=(document.getElementById('m-title') as HTMLInputElement).value.trim();if(!roomId||title.length<2){Swal.showValidationMessage('กรอกห้องและรายละเอียด');return false;}return{roomId,title};}});if(!r.value)return;await createMaintenance(propertyId,r.value);await Promise.all([load(),refetchDashboard()]);await showSuccess('บันทึกแจ้งซ่อมสำเร็จ','ข้อมูลและการแจ้งเตือนถูกสร้างใน SQL แล้ว');}catch(e){showError('บันทึกไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};
const setStatus=async(id:string,status:MaintenanceRecord['status'])=>{if(!propertyId)return;try{await updateMaintenance(propertyId,id,{status});await Promise.all([load(),refetchDashboard()]);}catch(e){showError('อัปเดตไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};
return <div className="space-y-6"><ModuleHeader title="แจ้งซ่อม & งานช่าง" subtitle={`งานค้างจาก SQL ${summary?.maintenance.open??0} รายการ`} icon={Wrench} actionLabel="+ แจ้งซ่อม" onAction={add}/><div className="rounded-2xl border bg-white p-4"><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} className="h-10 rounded-xl border px-3 text-sm"><option value="ALL">ทุกสถานะ</option><option value="PENDING">รอดำเนินการ</option><option value="IN_PROGRESS">กำลังซ่อม</option><option value="DONE">เสร็จแล้ว</option><option value="CANCELLED">ยกเลิก</option></select></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-surface-50 text-xs text-surface-500"><tr><th className="px-5 py-3">ห้อง</th><th className="px-4 py-3">รายการ</th><th className="px-4 py-3">วันที่แจ้ง</th><th className="px-5 py-3">สถานะ</th></tr></thead><tbody className="divide-y">{items.map(m=><tr key={m.id}><td className="px-5 py-3 font-bold">ห้อง {m.room.number}</td><td className="px-4 py-3">{m.title}</td><td className="px-4 py-3 text-xs">{formatThaiDateTime(m.createdAt)}</td><td className="px-5 py-3"><select value={m.status} onChange={e=>void setStatus(m.id,e.target.value as MaintenanceRecord['status'])} className="rounded-lg border px-2 py-1 text-xs"><option value="PENDING">รอดำเนินการ</option><option value="IN_PROGRESS">กำลังซ่อม</option><option value="DONE">เสร็จแล้ว</option><option value="CANCELLED">ยกเลิก</option></select></td></tr>)}</tbody></table></div></div>};
