import React, { useCallback, useEffect, useState } from 'react';
import { MessageSquareMore } from 'lucide-react';
import { ModuleHeader } from '../components/shared/ModuleHeader';
import { useDashboard } from '../context/DashboardContext';
import { listNotifications, markAllNotificationsAsRead, markNotificationAsRead } from '../lib/api';
import { showError, showSuccess } from '../lib/alert';
import { formatThaiDateTime } from '../lib/format';
import type { AppNotification } from '../types';

export const MessagesPage:React.FC=()=>{const{summary,refetch:refetchDashboard}=useDashboard();const propertyId=summary?.property.id;const[items,setItems]=useState<AppNotification[]>([]);const[unread,setUnread]=useState(0);const load=useCallback(async()=>{if(!propertyId)return;try{const r=await listNotifications(propertyId);setItems(r.items);setUnread(r.unread);}catch(e){showError('โหลดข้อความไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}},[propertyId]);useEffect(()=>{void load();},[load]);const read=async(n:AppNotification)=>{if(!propertyId||n.readAt)return;await markNotificationAsRead(propertyId,n.id);await Promise.all([load(),refetchDashboard()]);};const readAll=async()=>{if(!propertyId)return;try{const r=await markAllNotificationsAsRead(propertyId);await Promise.all([load(),refetchDashboard()]);await showSuccess('อ่านทั้งหมดแล้ว',`อัปเดต ${r.updated} รายการใน PostgreSQL`);}catch(e){showError('อัปเดตไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};return <div className="space-y-6"><ModuleHeader title="ข้อความ & การแจ้งเตือน" subtitle={`กล่องข้อความระบบจาก PostgreSQL · ยังไม่ได้อ่าน ${unread}`} icon={MessageSquareMore} actionLabel="อ่านทั้งหมด" onAction={readAll}/><div className="space-y-3">{items.length===0?<div className="rounded-2xl border bg-white p-10 text-center text-sm text-surface-400">ยังไม่มีข้อความระบบ</div>:items.map(n=><button key={n.id} onClick={()=>void read(n)} className={`w-full rounded-2xl border p-4 text-left shadow-sm ${n.readAt?'bg-white':'border-primary-200 bg-primary-50/40'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-surface-900">{n.title}</p><p className="mt-1 text-sm text-surface-600">{n.body}</p></div>{!n.readAt&&<span className="rounded-full bg-primary-600 px-2 py-1 text-[10px] font-bold text-white">ใหม่</span>}</div><p className="mt-2 text-xs text-surface-400">{formatThaiDateTime(n.createdAt)}</p></button>)}</div><p className="text-xs text-surface-400">หน้านี้แสดงข้อความ/การแจ้งเตือนที่ Backend บันทึกจริง เช่น ชำระเงิน แจ้งซ่อม สัญญาใกล้หมด และห้องว่าง</p></div>};
