import React, { useEffect, useState } from 'react';
import { Settings } from 'lucide-react';
import { ModuleHeader } from '../components/shared/ModuleHeader';
import { useDashboard } from '../context/DashboardContext';
import { getProperty, updateProperty } from '../lib/api';
import { showError, showSuccess } from '../lib/alert';
import type { PropertyType } from '../types';

export const SettingsPage:React.FC=()=>{const{summary,refetch}=useDashboard();const propertyId=summary?.property.id;const[name,setName]=useState('');const[type,setType]=useState<PropertyType>('CONDO');const[typeLabel,setTypeLabel]=useState('');const[counts,setCounts]=useState<{rooms:number;tenants:number;expenses:number;notifications:number}|null>(null);useEffect(()=>{if(!propertyId)return;void getProperty(propertyId).then(p=>{setName(p.name);setType(p.type);setTypeLabel(p.typeLabel??'');setCounts(p._count??null);}).catch(e=>showError('โหลดการตั้งค่าไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด'));},[propertyId]);const save=async()=>{if(!propertyId||name.trim().length<2)return;try{await updateProperty(propertyId,{name:name.trim(),type,typeLabel:typeLabel.trim()||null});await refetch();await showSuccess('บันทึกการตั้งค่าสำเร็จ','ข้อมูลโครงการถูกอัปเดตใน PostgreSQL แล้ว');}catch(e){showError('บันทึกไม่สำเร็จ',e instanceof Error?e.message:'เกิดข้อผิดพลาด');}};return <div className="space-y-6"><ModuleHeader title="ตั้งค่าระบบ" subtitle="แก้ไขข้อมูลโครงการจริงใน PostgreSQL" icon={Settings} actionLabel="บันทึกการตั้งค่า" onAction={save}/><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm lg:col-span-2"><label className="block text-sm font-semibold">ชื่อโครงการ<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal" /></label><label className="block text-sm font-semibold">ประเภท<select value={type} onChange={e=>setType(e.target.value as PropertyType)} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal"><option value="CONDO">CONDO</option><option value="ROOM_RENTAL">ROOM_RENTAL</option><option value="APARTMENT">APARTMENT</option><option value="DORMITORY">DORMITORY</option><option value="COMMERCIAL">COMMERCIAL</option><option value="OTHER">OTHER</option></select></label><label className="block text-sm font-semibold">ชื่อประเภทที่แสดง<input value={typeLabel} onChange={e=>setTypeLabel(e.target.value)} placeholder="เช่น คอนโด / ห้องเช่า" className="mt-2 h-10 w-full rounded-xl border px-3 font-normal" /></label><div className="rounded-xl bg-surface-50 p-3 text-xs text-surface-500">แพ็กเกจปัจจุบัน: <b>{summary?.property.plan}</b> · สิทธิ์ผู้ใช้: <b>{summary?.user.role}</b></div></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">ข้อมูลในฐานข้อมูล</h3><div className="mt-4 space-y-3 text-sm"><Row label="ห้อง" value={counts?.rooms??summary?.rooms.total??0}/><Row label="ผู้เช่า" value={counts?.tenants??summary?.tenants.total??0}/><Row label="รายจ่าย" value={counts?.expenses??0}/><Row label="การแจ้งเตือน" value={counts?.notifications??0}/></div></div></div></div>};
const Row:React.FC<{label:string;value:number}>=({label,value})=><div className="flex justify-between border-b pb-2"><span className="text-surface-500">{label}</span><b>{value}</b></div>;
